@startuml database "Library" {
/' Settings '/
hide circle
hide empty methods
skinparam linetype polyline

/' Entities '/
entity Book {
    id : int **<<PI>>**
    title : varchar
    image: bytea
}

entity Author {
    id : int **<<PI>>**
    name : varchar
}

entity Genre {
    name : varchar **<<PI>>**
}

entity Account {
    name : varchar **<<PI>>**
    email : varchar
    password : varchar
}

/' Relationships '/
Author ||-right-o{ Book : "are written by"
Genre ||--o{ Book: "are of"
Account }o-left-o{ Book : "Sold"
Account }o-left-o{ Book : "Bought"
Account }o-left-o{ Book : "Borrowed"